name: Deploy to S3

on:
  push:
    branches:
      - master # Modify this to match your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Yarn
        run: |
          npm install -g yarn
      # Use the npm installer to install yarn globally

      - name: Install Dependencies
        run: yarn install
      # Replace "npm install" with "yarn install"

      - name: Build React App
        run: yarn build
      # Replace "npm run build" with "yarn build"

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
          aws-region: ap-south-1
  
      - name: Deploy to S3 bucket
        run: aws s3 sync ./out s3://hkpsbucket --delete
